use crate::{
    runtime::{
        cli::{RunArgs, StartArgs},
        options::{
            ResolvedVisualOptions, default_color_mode_for_mode, resolve_effective_color_mode,
        },
    },
    scene::{RenderConfig, RenderMode, StageRole, SyncPolicy},
};

struct RenderConfigInput {
    mode: RenderMode,
    fov_deg: f32,
    near: f32,
    far: f32,
    charset: String,
    cell_aspect: f32,
    fps_cap: u32,
    ambient: f32,
    diffuse_strength: f32,
    specular_strength: f32,
    specular_power: f32,
    rim_strength: f32,
    rim_power: f32,
    fog_strength: f32,
    sync_policy: SyncPolicy,
    sync_hard_snap_ms: u32,
    sync_kp: f32,
}

fn build_render_config(input: RenderConfigInput, visual: &ResolvedVisualOptions) -> RenderConfig {
    let color_mode = resolve_effective_color_mode(
        input.mode,
        visual
            .color_mode
            .unwrap_or_else(|| default_color_mode_for_mode(input.mode)),
        visual.ascii_force_color,
    );
    RenderConfig {
        fov_deg: input.fov_deg,
        near: input.near,
        far: input.far,
        mode: input.mode,
        output_mode: visual.output_mode,
        graphics_protocol: visual.graphics_protocol,
        kitty_transport: visual.kitty_transport,
        kitty_compression: visual.kitty_compression,
        kitty_internal_res: visual.kitty_internal_res,
        kitty_pipeline_mode: visual.kitty_pipeline_mode,
        recover_strategy: visual.recover_strategy,
        kitty_scale: visual.kitty_scale,
        hq_target_fps: visual.hq_target_fps,
        subject_exposure_only: visual.subject_exposure_only,
        subject_target_height_ratio: visual.subject_target_height_ratio,
        subject_target_width_ratio: visual.subject_target_width_ratio,
        quality_auto_distance: visual.quality_auto_distance,
        texture_mip_bias: visual.texture_mip_bias,
        stage_as_sub_only: visual.stage_as_sub_only,
        stage_role: if visual.stage_as_sub_only {
            StageRole::Sub
        } else {
            visual.stage_role
        },
        stage_luma_cap: visual.stage_luma_cap,
        recover_color_auto: visual.recover_color_auto,
        perf_profile: visual.perf_profile,
        detail_profile: visual.detail_profile,
        backend: visual.backend,
        color_mode,
        ascii_force_color: visual.ascii_force_color,
        braille_profile: visual.braille_profile,
        theme_style: visual.theme_style,
        audio_reactive: visual.audio_reactive,
        cinematic_camera: visual.cinematic_camera,
        camera_focus: visual.camera_focus,
        reactive_gain: visual.reactive_gain,
        reactive_pulse: 0.0,
        exposure_bias: visual.exposure_bias,
        center_lock: visual.center_lock,
        center_lock_mode: visual.center_lock_mode,
        stage_level: visual.stage_level,
        stage_quality: visual.stage_quality,
        stage_reactive: visual.stage_reactive,
        material_color: visual.material_color,
        texture_sampling: visual.texture_sampling,
        texture_v_origin: visual.texture_v_origin,
        texture_sampler: visual.texture_sampler,
        clarity_profile: visual.clarity_profile,
        ansi_quantization: visual.ansi_quantization,
        model_lift: visual.model_lift,
        edge_accent_strength: visual.edge_accent_strength,
        bg_suppression: visual.bg_suppression,
        braille_aspect_compensation: visual.braille_aspect_compensation,
        charset: input.charset,
        cell_aspect: input.cell_aspect,
        cell_aspect_mode: visual.cell_aspect_mode,
        cell_aspect_trim: visual.cell_aspect_trim,
        fps_cap: input.fps_cap,
        ambient: input.ambient,
        diffuse_strength: input.diffuse_strength,
        specular_strength: input.specular_strength,
        specular_power: input.specular_power,
        rim_strength: input.rim_strength,
        rim_power: input.rim_power,
        fog_strength: input.fog_strength,
        contrast_profile: visual.contrast_profile,
        sync_policy: input.sync_policy,
        sync_hard_snap_ms: input.sync_hard_snap_ms,
        sync_kp: input.sync_kp,
        contrast_floor: 0.10,
        contrast_gamma: 0.90,
        fog_scale: 1.0,
        triangle_stride: 1,
        min_triangle_area_px2: 0.0,
    }
}

pub(crate) fn render_config_from_run(
    args: &RunArgs,
    visual: &ResolvedVisualOptions,
) -> RenderConfig {
    build_render_config(
        RenderConfigInput {
            mode: args.mode.into(),
            fov_deg: args.fov_deg,
            near: args.near,
            far: args.far,
            charset: args.charset.clone(),
            cell_aspect: args.cell_aspect,
            fps_cap: args.fps_cap,
            ambient: args.ambient,
            diffuse_strength: args.diffuse_strength,
            specular_strength: args.specular_strength,
            specular_power: args.specular_power,
            rim_strength: args.rim_strength,
            rim_power: args.rim_power,
            fog_strength: args.fog_strength,
            sync_policy: SyncPolicy::Continuous,
            sync_hard_snap_ms: 120,
            sync_kp: 0.15,
        },
        visual,
    )
}

pub(crate) fn render_config_from_start(
    args: &StartArgs,
    visual: &ResolvedVisualOptions,
) -> RenderConfig {
    build_render_config(
        RenderConfigInput {
            mode: args.mode.into(),
            fov_deg: args.fov_deg,
            near: args.near,
            far: args.far,
            charset: args.charset.clone(),
            cell_aspect: args.cell_aspect,
            fps_cap: args.fps_cap,
            ambient: args.ambient,
            diffuse_strength: args.diffuse_strength,
            specular_strength: args.specular_strength,
            specular_power: args.specular_power,
            rim_strength: args.rim_strength,
            rim_power: args.rim_power,
            fog_strength: args.fog_strength,
            sync_policy: SyncPolicy::Continuous,
            sync_hard_snap_ms: 120,
            sync_kp: 0.15,
        },
        visual,
    )
}

pub(crate) fn render_config_for_bench(
    mode: RenderMode,
    fov_deg: f32,
    near: f32,
    far: f32,
    charset: String,
    cell_aspect: f32,
    ambient: f32,
    diffuse_strength: f32,
    specular_strength: f32,
    specular_power: f32,
    rim_strength: f32,
    rim_power: f32,
    fog_strength: f32,
    sync_policy: SyncPolicy,
    sync_hard_snap_ms: u32,
    sync_kp: f32,
    visual: &ResolvedVisualOptions,
) -> RenderConfig {
    build_render_config(
        RenderConfigInput {
            mode,
            fov_deg,
            near,
            far,
            charset,
            cell_aspect,
            fps_cap: u32::MAX,
            ambient,
            diffuse_strength,
            specular_strength,
            specular_power,
            rim_strength,
            rim_power,
            fog_strength,
            sync_policy,
            sync_hard_snap_ms,
            sync_kp,
        },
        visual,
    )
}
